### PR TITLE
Nawqaan 610 Duplicate loads tests, resolving merge conflicts

### PR DESCRIPTION
**Pull request by cschroed-usgs**

### CODE REVIEW

**Comment by cschroed-usgs** [comment]
@supercasey can you confirm which columns should uniquely identify a load observation whose modtype is not CONTIN or COMP? I proposed ('SITE_QW_ID', 'CONSTIT', 'WY'). Previously, it involved SITE_ABB.

**Comment by cschroed-usgs** [comment]
The [failure of these tests on Travis](https://travis-ci.org/USGS-CIDA/nar_data/builds/153308368#L865) combined with the intentional insertion of duplicate load values ([here](https://github.com/USGS-CIDA/nar_data/pull/39/files#diff-49fd090d4c14eef79d0b59806a360ebfR100) and [here](https://github.com/USGS-CIDA/nar_data/pull/39/files#diff-ffb8890eaa0ebdfa52a9ce26e427c033R112)) emphasizes that our tests can catch bad data. Next I will push an update that removes the intentional insertion of a duplication row.

**Comment by supercasey** [comment]
That is correct, I confirmed that there aren't duplicates on that combination for aloads or mloads.

**Comment by cschroed-usgs** [comment]
Thank you for confirming!

**Comment by cschroed-usgs** [comment]
Merging since the tests passed after removing the intentional duplicates.

**Pull request merged**
